"""baseline

Revision ID: 19803cfc3904
Revises: 
Create Date: 2026-07-07 19:58:48.478333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19803cfc3904'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('championship_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('team_name', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('points', sa.Float(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_championship_standings_category'), 'championship_standings', ['category'], unique=False)
    op.create_index(op.f('ix_championship_standings_year'), 'championship_standings', ['year'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('country_image_url', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('finish_date', sa.Date(), nullable=True),
    sa.Column('current_leader', sa.String(), nullable=True),
    sa.Column('current_leader_logo_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('overall_standings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('diff_to_first', sa.String(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('position_change', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_overall_standings_event_id'), 'overall_standings', ['event_id'], unique=False)
    op.create_table('stage_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=True),
    sa.Column('entry_id', sa.Integer(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('logo_path', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('time', sa.String(), nullable=True),
    sa.Column('diff_to_first', sa.String(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('last_split_id', sa.Integer(), nullable=True),
    sa.Column('position_change', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stage_times_stage_id'), 'stage_times', ['stage_id'], unique=False)
    op.create_table('stages',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=True),
    sa.Column('winner_name', sa.String(), nullable=True),
    sa.Column('winner_logo_path', sa.String(), nullable=True),
    sa.Column('winner_time', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stages_event_id'), 'stages', ['event_id'], unique=False)
    op.create_table('timeline_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('message', sa.String(), nullable=True),
    sa.Column('driver_number', sa.String(), nullable=True),
    sa.Column('driver_name', sa.String(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_session_id'), 'timeline_events', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_session_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_stages_event_id'), table_name='stages')
    op.drop_table('stages')
    op.drop_index(op.f('ix_stage_times_stage_id'), table_name='stage_times')
    op.drop_table('stage_times')
    op.drop_index(op.f('ix_overall_standings_event_id'), table_name='overall_standings')
    op.drop_table('overall_standings')
    op.drop_table('events')
    op.drop_index(op.f('ix_championship_standings_year'), table_name='championship_standings')
    op.drop_index(op.f('ix_championship_standings_category'), table_name='championship_standings')
    op.drop_table('championship_standings')
    # ### end Alembic commands ###
