"""add_event_briefings_table

Revision ID: 35052ecbe6cf
Revises: 28c8de6193d8
Create Date: 2026-08-03 19:00:04.725169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35052ecbe6cf'
down_revision: Union[str, Sequence[str], None] = '28c8de6193d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_briefings',
    sa.Column('event_id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('surface_type_pt', sa.String(), nullable=True),
    sa.Column('surface_type_en', sa.String(), nullable=True),
    sa.Column('tactical_briefing_pt', sa.String(), nullable=True),
    sa.Column('tactical_briefing_en', sa.String(), nullable=True),
    sa.Column('last_winner', sa.String(), nullable=True),
    sa.Column('event_record', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_event_briefings_category'), 'event_briefings', ['category'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_briefings_category'), table_name='event_briefings')
    op.drop_table('event_briefings')
    # ### end Alembic commands ###
