import logging
from datetime import datetime, timezone
from typing import Optional

from fastapi import APIRouter, HTTPException, Query, Depends, Request

from core.redis_service import get_cached_data
from ingestion.openf1_client import fetch_f1_race_control_messages
from models.timeline import TimelineResponse, TimelineEvent

logger = logging.getLogger(__name__)

from core.security import verify_client_token, verify_app_check_token
from core.rate_limit import limiter

router = APIRouter(
    prefix="/api/v1/timeline", 
    tags=["Timeline"],
    dependencies=[Depends(verify_client_token), Depends(verify_app_check_token)],
)

@router.get("/{category}/{session_id}", response_model=TimelineResponse)
@limiter.limit("60/minute")
async def get_timeline(
    request: Request,
    category: str,
    session_id: str,
    event_id: str = Query(..., description="The overarching event ID"),
    last_event_time: Optional[datetime] = Query(None, description="Fetch only events after this time (Smart Polling)"),
    language: str = Query("pt", description="Language for the commentary (e.g., 'en', 'pt'). Defaults to 'pt'.")
):
    """
    Get the live timeline of events for a specific session.
    Implements Smart Polling via the last_event_time query parameter.
    """
    all_events = []
    
    if category.lower() == "f1":
        # Ensure session_id is castable to int since OpenF1 uses session_key
        try:
            session_key = int(session_id)
        except ValueError:
            raise HTTPException(status_code=400, detail="F1 session_id must be an integer (session_key).")
            
        timeline_key = f"timeline:f1:{session_key}"
        raw_events = await get_cached_data(timeline_key)
        if raw_events:
            all_events = [TimelineEvent(**e) for e in raw_events]
        else:
            all_events = await fetch_f1_race_control_messages(session_key)
            if all_events:
                from core.redis_service import set_cached_data
                # Cache for 60 seconds to avoid hammering OpenF1 and Twitter
                await set_cached_data(timeline_key, [e.model_dump(mode='json') for e in all_events], expiration_seconds=60)
            
    elif category.lower() == "wrc":
        # WRC Data: Generated by Agent 03 and cached in Redis
        timeline_key = f"timeline:wrc:{session_id}"
        raw_events = await get_cached_data(timeline_key)
        if raw_events:
            all_events = [TimelineEvent(**e) for e in raw_events]
        else:
            from core.database_service import get_timeline_events_from_db
            db_events = await get_timeline_events_from_db(session_id)
            if not db_events:
                # Use a Redis lock to prevent race condition of multiple concurrent requests writing duplicate events
                from core.redis_service import redis_client
                import asyncio
                lock_key = f"lock:populate_historic:{session_id}"
                acquired = await redis_client.set(lock_key, "1", nx=True, ex=30)
                
                if acquired:
                    try:
                        from ingestion.service import populate_historic_timeline
                        # session_id should be cast to int for WRC stages
                        db_events = await populate_historic_timeline(int(session_id))
                    except ValueError:
                        await redis_client.delete(lock_key)
                        raise HTTPException(status_code=400, detail="WRC session_id must be an integer (stage_id).")
                    finally:
                        await redis_client.delete(lock_key)
                else:
                    # If we couldn't acquire the lock, another request is currently extracting the data.
                    # We perform dynamic polling (up to 15 seconds) waiting for the other request to finish.
                    for _ in range(15):
                        await asyncio.sleep(1)
                        db_events = await get_timeline_events_from_db(session_id)
                        if db_events:
                            break
                
            if db_events:
                # Deduplicate by message to prevent race condition duplicates
                seen_messages = set()
                all_events = []
                for e in db_events:
                    if e.message not in seen_messages:
                        seen_messages.add(e.message)
                        all_events.append(e)
                
                # Re-warm cache
                from core.redis_service import set_cached_data
                await set_cached_data(timeline_key, [e.model_dump(mode='json') for e in all_events], expiration_seconds=86400)
    else:
        raise HTTPException(status_code=404, detail="Category not supported.")
    
    # Apply Smart Polling filter
    if last_event_time:
        # Ensure UTC comparison
        if last_event_time.tzinfo is None:
             last_event_time = last_event_time.replace(tzinfo=timezone.utc)
             
        def is_newer(event):
            evt_ts = event.timestamp
            if evt_ts.tzinfo is None:
                evt_ts = evt_ts.replace(tzinfo=timezone.utc)
            return evt_ts > last_event_time
             
        filtered_events = [event for event in all_events if is_newer(event)]
    else:
        filtered_events = all_events
        
    # Apply Language Mapping
    lang_key = f"message_{language.lower()}"
    for event in filtered_events:
        if event.metadata and lang_key in event.metadata:
            event.message = event.metadata[lang_key]
        
    return TimelineResponse(
        event_id=event_id,
        session_id=session_id,
        events=filtered_events
    )
