from fastapi import APIRouter, HTTPException, Query, Path
from datetime import datetime, timezone, timedelta
from typing import Optional
import logging

from models.timeline import TimelineResponse, TimelineEvent, TimelineEventSource, TimelineEventSeverity
from ingestion.openf1_client import fetch_f1_race_control_messages
from core.redis_service import get_cached_data

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/api/v1/timeline", tags=["Timeline"])

@router.get("/{category}/{session_id}", response_model=TimelineResponse)
async def get_timeline(
    category: str,
    session_id: str,
    event_id: str = Query(..., description="The overarching event ID"),
    last_event_time: Optional[datetime] = Query(None, description="Fetch only events after this time (Smart Polling)"),
    language: str = Query("pt", description="Language for the commentary (e.g., 'en', 'pt'). Defaults to 'pt'.")
):
    """
    Get the live timeline of events for a specific session.
    Implements Smart Polling via the last_event_time query parameter.
    """
    all_events = []
    
    if category.lower() == "f1":
        # Ensure session_id is castable to int since OpenF1 uses session_key
        try:
            session_key = int(session_id)
            all_events = await fetch_f1_race_control_messages(session_key)
        except ValueError:
            raise HTTPException(status_code=400, detail="F1 session_id must be an integer (session_key).")
            
    elif category.lower() == "wrc":
        # WRC Data: Generated by Agent 03 and cached in Redis
        timeline_key = f"timeline:wrc:{session_id}"
        raw_events = await get_cached_data(timeline_key)
        if raw_events:
            all_events = [TimelineEvent(**e) for e in raw_events]
        else:
            all_events = []
    else:
        raise HTTPException(status_code=404, detail="Category not supported.")
    
    # Apply Smart Polling filter
    if last_event_time:
        # Ensure UTC comparison
        if last_event_time.tzinfo is None:
             last_event_time = last_event_time.replace(tzinfo=timezone.utc)
             
        filtered_events = [event for event in all_events if event.timestamp > last_event_time]
    else:
        filtered_events = all_events
        
    # Apply Language Mapping
    lang_key = f"message_{language.lower()}"
    for event in filtered_events:
        if event.metadata and lang_key in event.metadata:
            event.message = event.metadata[lang_key]
        
    return TimelineResponse(
        event_id=event_id,
        session_id=session_id,
        events=filtered_events
    )
