from pydantic import BaseModel, Field
from typing import Optional, List, Dict, Any
from enum import Enum
from datetime import datetime

class TimelineEventSeverity(str, Enum):
    INFO = "info"          # Normal events (e.g., "Neuville started the stage", Green flag)
    WARNING = "warning"    # Incidents, slow sectors (e.g., "Ogier lost 3 mins", Yellow flag)
    CRITICAL = "critical"  # Severe incidents (e.g., "Car stopped on track", Red flag)

class TimelineEventSource(str, Enum):
    F1_RACE_CONTROL = "f1_race_control"        # Official F1 API race control messages
    WRC_SYSTEM_INFERENCE = "wrc_system_inference" # Generated by our backend based on split times
    WRC_SOCIAL_MEDIA = "wrc_social_media"      # Scraped/Fetched from Twitter or official sources

class TimelineEvent(BaseModel):
    """
    Represents a single play-by-play or commentary event in the timeline.
    """
    id: str = Field(..., description="Unique identifier for the timeline event")
    timestamp: datetime = Field(..., description="UTC datetime of the event")
    source: TimelineEventSource = Field(..., description="The system source of this event")
    severity: TimelineEventSeverity = Field(default=TimelineEventSeverity.INFO, description="Severity level for UI color coding")
    message: str = Field(..., description="The main text of the commentary (e.g., 'CAR 1 (VER) STOPPED ON TRACK')")
    
    # Optional context mapping
    driver_number: Optional[str] = Field(None, description="Driver number if the event is tied to a specific car")
    driver_name: Optional[str] = Field(None, description="Driver name if known/applicable")
    
    # Flexible metadata dictionary for source-specific attributes
    metadata: Optional[Dict[str, Any]] = Field(
        default_factory=dict, 
        description="Extra raw data. For F1: lap_number, flag. For WRC: split_id, tweet_url."
    )

class TimelineResponse(BaseModel):
    """
    The unified response payload that the Android App will consume for the Live Timeline feature.
    """
    event_id: str = Field(..., description="The overarching event ID (e.g., rally_portugal_2024 or f1_monaco_2024)")
    session_id: str = Field(..., description="The specific session ID (e.g., SS12 or F1_RACE)")
    events: List[TimelineEvent] = Field(default_factory=list, description="Chronological list of timeline events")
